added router
keiryan/Crypto-App pull request #1
Opened 2022-06-30 16:18 UTC by keiryan

Fixed the incorrect routing that would not switch pages.

2022-06-30 16:57 UTC, yoloOnTheBattlefield reviewed
https://developer-pro.mykajabi.com/products/react-pro/categories/2149030003/posts/2152230042

2022-06-30 16:57 UTC, yoloOnTheBattlefield commented on src/App.js
> +// import CoinContainer from "./components/CoinContainer/coincontainer";
no commented out code

2022-06-30 16:57 UTC, yoloOnTheBattlefield commented on src/utils/MarketCap/index.js
>      // }
no commented out code

2022-07-05 14:36 UTC, keiryan commented
**### Pull Request 2 Change log:**

- Implemented coin API
- Updated absolute imports in App.js
- Added bold coin name styling
- Fixed number abbreviator algorithm
- Coin percentages have been moved to` <abbr>` tags to reduce space taken overall. The full percentage can be seen by hovering over the desired percentage.
- Barchart numbers have also been moved to` <abbr>` tags if full number is desired to be seen.
- Scroll bar has been set to a custom color to reduce intrusion.
- Removed all `console.log()’`s
- Removed unnecessary commented out code

2022-07-05 17:55 UTC, yoloOnTheBattlefield requested changes

2022-07-05 17:55 UTC, yoloOnTheBattlefield commented on src/components/Navbar/navbar.styles.js
> +import { Link } from 'react-router-dom'
absolute before relative

2022-07-05 17:55 UTC, yoloOnTheBattlefield commented on src/pages/Coinpage/coinpage.js
> +import axios from 'axios';
absolute before relative

2022-07-08 21:00 UTC, merged